### ISSUE TITLE
Dynamic execution problem

### ISSUE THREAD

**Issue by morangeous** [ExpoSEJS/ExpoSE#82]
Hi
I just wonder how to handle the dynamic execution. In my case, the program stopped in this step:

>expoSE "https://www.google.com"

> Web Mode, Starting Proxy

I have all of the dependencies including mitmproxy and python.
Thanks !

**Comment by jawline** [comment]
Hi! Can you give me the MITMProxy output? It will be placed in a random file like /tmp/mitmlog.zSW1vUXkE which will be reported in the initial output.

**Comment by morangeous** [comment]
ok, this is my log file, do you know where is the problem?

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urwid 2.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('urwid<1.4,>=1.3.1'), {'mitmproxy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mitmdump", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urwid<1.4,>=1.3.1' distribution was not found and is required by mitmproxy

Really thanks!

**Comment by morangeous** [comment]
Thank God!
Finally, I get what is the problem.
I download mitmproxy by the command:

> sudo apt-get install mitmproxy

And it doesn't work.
The following command can get you out when you meet the same question:

> sudo pip3 install -U pip

> sudo pip3 install mitmproxy

In the end, thank you a lot @jawline
